package com.test.material.supitsara.materialnavigationtest;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SEARCH.
 */
public class Search {

    private Long id;
    private String userID;
    private String keyword;

    public Search() {
    }

    public Search(Long id) {
        this.id = id;
    }

    public Search(Long id, String userID, String keyword) {
        this.id = id;
        this.userID = userID;
        this.keyword = keyword;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserID() {
        return userID;
    }

    public void setUserID(String userID) {
        this.userID = userID;
    }

    public String getKeyword() {
        return keyword;
    }

    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }

}
