package com.test.material.supitsara.materialnavigationtest;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TOUR.
 */
public class Tour {

    private Long id;
    private String userID;
    private String boothID;
    private Double Lat;
    private Double Long;

    public Tour() {
    }

    public Tour(Long id) {
        this.id = id;
    }

    public Tour(Long id, String userID, String boothID, Double Lat, Double Long) {
        this.id = id;
        this.userID = userID;
        this.boothID = boothID;
        this.Lat = Lat;
        this.Long = Long;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserID() {
        return userID;
    }

    public void setUserID(String userID) {
        this.userID = userID;
    }

    public String getBoothID() {
        return boothID;
    }

    public void setBoothID(String boothID) {
        this.boothID = boothID;
    }

    public Double getLat() {
        return Lat;
    }

    public void setLat(Double Lat) {
        this.Lat = Lat;
    }

    public Double getLong() {
        return Long;
    }

    public void setLong(Double Long) {
        this.Long = Long;
    }

}
